server:
  port: 6001
  
jwt:
  secret: Key#SuperSecret$PolyglotTest#JavaMicroservices#940527000
  
spring:
  application:
    name: appgateway
  cloud:
   gateway:
    discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
        default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
    routes:      
      - id: apppersonas
        uri: http://localhost:81
        predicates:
          - Path=/personas/**
        filters:
          - StripPrefix=1
          - JwtAuthenticationFilter
      - id: appcursos
        uri: http://localhost:82
        predicates:
          - Path=/materia/**
        filters:
          - StripPrefix=1
          - JwtAuthenticationFilter
      - id: appmatricula
        uri: http://localhost:83
        predicates:
          - Path=/matricula/**
        filters:
          - StripPrefix=1
          - JwtAuthenticationFilter
      - id: appseguridad
        uri: http://localhost:84
        predicates:
          - Path=/seguridad/**
        filters:
          - StripPrefix=1
      - id: apppago
        uri: http://localhost:85
        predicates:
          - Path=/pagos/**
        filters:
          - StripPrefix=1
          - JwtAuthenticationFilter